### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by abacon** [MichelleGlauser/techtonica#1]
Because techtonica wants to serve folks who may have limited (or metered) internet access, having a low-footprint and fast website is important. I'm documenting the specific items raised by Michelle on the FB image, reproduced below. They can also be verified via the chrome pagespeed insights extension.

![13719511_10154302863853698_4920285699213916947_o](https://cloud.githubusercontent.com/assets/903181/16976712/a2c90be8-4e05-11e6-8e06-6bee494e1fd8.jpg)

The specific high-impact/priority items on the list are:
- [ ] Enable compression
- [ ] Minify JS
- [ ] Serve scaled images
- [ ] Enable keep-alive

**Comment by abacon** [comment]
Now that I think about it, 'enable compression' and 'enable keep-alive' are settings for whatever is serving the site. So we can't really address them until we've decided on and have documented how/where we're deploying. @MichelleGlauser what's the hosting situation?

**Comment by MichelleGlauser** [comment]
It's on [Bluehost](http://bluehost.com).

**Comment by moagm316** [comment]
I was working on compressing some of the if not all of the images for the site but the compression that I was getting was not hat effective.

**Comment by moagm316** [comment]
Flask-Assets allows you to pipeline your assets.

http://exploreflask.com/en/latest/static.html

**Comment by hagata** [comment]
Hi! 👋
What is the status of this issue? I'd love to help optimize the site performance and build process. We have an opportunity to help out the load time on slow internet and mobile; this seems to be highly valuable.

I'd be happy to tackle #4 with Gulp, or Webpack! It would be great to get some developer conveniences into the toolchain–like auto reload/rebuild. I can also help get images optimized site-wide, getting the file sizes down as well as adding the right resolutions to serve for each screen situation, e.g., @2x files. 

Cheers!

**Comment by MichelleGlauser** [comment]
@hagata, as far as I know, no one has touched this. You're welcome to do it with Gulp or Webpack and to add the other things like auto reload/rebuild!

**Comment by hagata** [comment]
Thanks, @MichelleGlauser!
I noticed this project relies on CodeKit. I'll probably implement Sass as part of the build process. Is CodeKit something you would like to maintain supporting, even if the build process did the Sass processing?

**Comment by MichelleGlauser** [comment]
Hmm, that would be a question for @harrystaley. (I didn't set up CodeKit and I just compile Sass before pushing.)

**Comment by hagata** [comment]
no problem! Thanks.

**Comment by harrystaley** [comment]
Hmm I did not add code kit, but google page speed just ran below.

https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.techtonica.org%2F&tab=desktop

**Comment by hagata** [comment]
In any case, I added codekit files to .gitignore in a previous PR

**Comment by KGmajor** [comment]
Closing due to duplication
