### ISSUE TITLE
Figure out why /careers padding differs between staging and live 

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#105]
There's more space around footer icons when served locally and on staging. 

Served locally (looks the same on staging):
![screen shot 2017-06-10 at 10 43 53 am](https://user-images.githubusercontent.com/1952773/27005037-5919ef88-4dca-11e7-96e4-a6dd0fc46ef3.png)

Live:
![screen shot 2017-06-10 at 10 43 46 am](https://user-images.githubusercontent.com/1952773/27005036-57dfc9da-4dca-11e7-9d0e-3630ca5a6b6e.png)

**Comment by amychan331** [comment]
@MichelleGlauser Are the code and css files loaded the same when you view the page with an inspector?

**Comment by gsong** [comment]
@MichelleGlauser They look identical to me when I load the two sites side-by-side in my Chrome browser, at various browser sizes.

**Comment by MichelleGlauser** [comment]
The CSS code is the same, @amychan331.
@gsong: interesting. I wonder why's it different on mine. @amychan331, do they look different to you?

**Comment by amychan331** [comment]
@MichelleGlauser Mine also look the same locally and on the techtonica site, with both looking like the local site image above.
I notice that the techtonica site image above have smaller font too. Is the browser zoom same for both local site and website? I think you can set them separately in Firefox. Not sure about Chrome.
