### ISSUE TITLE
Link the students' photos on the /sponsor page to their Medium stories

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#108]
You can find the student stories here: [medium.com/techtonica](http://medium.com/techtonica).

**Comment by CharleyMcLean** [comment]
I can work on this one after the weekend :) Should have a pull request ready at the beginning of the week beginning 7/23.

**Comment by CharleyMcLean** [comment]
@MichelleGlauser I'm looking at this now, but I don't see any students' photos on the [/sponsor](https://techtonica.org/sponsor/) page - is this something that is yet to come?

**Comment by MichelleGlauser** [comment]
Hi @CharleyMcLean, we just decided to take them down yesterday and I forgot to close this issue. Sorry about that! We could definitely use your help on some of the lesson templates for our curriculum, if that would interest you. Check out the needs here: https://docs.google.com/spreadsheets/d/1R8rBzR92KYg9HdFdEgVTrjVITnym8a4O61kthkJShiY/edit?usp=sharing
