### ISSUE TITLE
Add board photos, bios, and links to new team page

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#114]
Crop the images into squares, optimize them, make sure their titles are consistent with other images, add them to the repo, put them on the page. Then add the bios and links to the page, make sure everything looks good, and push.

[Photos, bios, and links here](https://drive.google.com/drive/folders/0B-htqvVE7J91S0sxVVBCZjg2STA?usp=sharing).

**Comment by joshualchan** [comment]
Finished with commits: 2c24bc, b2a4a5, d376df, and 1ac0ab
