### ISSUE TITLE
Fix main page so it goes back and forth between blue and white backgrounds.

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#135]

**Comment by MichelleGlauser** [comment]
This can be fixed with [the blue Eventbrite section proposed in issue 143](https://github.com/MichelleGlauser/techtonica/issues/143).

**Comment by hnarasaki** [comment]
Is this one done?

**Comment by KGmajor** [comment]
Fixed in a previous merge.
