### ISSUE TITLE
Navbar overlaps the main content

### ISSUE THREAD

**Issue by LizzHale** [MichelleGlauser/techtonica#21]
While working on the app today, I noticed that the navbar overlaps the main content. On the production website this is what the About page currently looks like for me using Chrome (didn't check with other browsers): 

<img width="1438" alt="screen shot 2016-09-24 at 6 41 45 pm" src="https://cloud.githubusercontent.com/assets/6598185/18812369/fd80ab80-8286-11e6-8f28-da808fe65f47.png">

This also affects the scrolling on the home page but the above was the most obvious to demonstrate in a screenshot.

I tried taking a look at what might be causing this or how to fix it but it wasn't obvious at first glance. I'll keep debugging but wanted to open this up in case someone else already knows the issue.

**Comment by MichelleGlauser** [comment]
I can't remember if it was like this before we put up the crowdfunding banner. @rosschapman, @ErinOC, and @moagm316, do you remember? We might have had it that way so people can easily switch between sections no matter where they are on the page.

**Comment by LizzHale** [comment]
> We might have had it that way so people can easily switch between sections no matter where they are on the page.

I might not have described the problem properly. Just in case, here's a gif to demonstrate the problem a bit better: 

![loading-scrolling](https://cloud.githubusercontent.com/assets/6598185/18817187/79c44084-830f-11e6-9afb-79c773ce7fac.gif)

Notice that when navigating to the various sections on the homepage, the navbar is covering much of the section (as if the anchor point is in the middle of the div, which it isn't). I think the sections `How it Works` and `How to Help` demonstrate this the best. Also when navigating to the `About Us` page, the navbar cuts off the top half of the main content div so that the picture and the words "About Us" are not visible.

**Comment by MichelleGlauser** [comment]
Arrrrrghhh, I see. The About Us page is especially bad.

**Comment by LizzHale** [comment]
Increasing the [top margin for the main content](https://github.com/MichelleGlauser/techtonica/blob/746bd19645a2cae8ad8400aca16984e2b644d920/static/css/style.css#L204-L205) seems to fix the problem for the about page. Doesn't seem to fix the scrolling. I'll deploy the fix for the about page and then keep working on the other
