### ISSUE TITLE
(Galaxy S5 landscape orientation) header background image not show properly

### ISSUE THREAD

**Issue by akshayvinchurkar** [MichelleGlauser/techtonica#24]
(Galaxy S5 landscape orientation) header background image does not show properly see this

![issue](https://cloud.githubusercontent.com/assets/10510889/20380298/2f2a7264-acc7-11e6-8527-de853d352157.png)

if you also think the same I can fix it.

**Comment by MichelleGlauser** [comment]
The header image doesn't show up at all on my iPhone 4S. Unfortunately I haven't had time to take a look. If you can figure out a solution, that would be great!

**Comment by akshayvinchurkar** [comment]
pull request #26 can fix this.

**Comment by akshayvinchurkar** [comment]
target each and every android device is lengthy task follow this simple media queries to create the best experience. just for information purpose.
https://css-tricks.com/snippets/css/media-queries-for-standard-devices/#phone-queries

**Comment by akshayvinchurkar** [comment]
since issue is fixed i closed this
