### ISSUE TITLE
Replace logo temporarily

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#34]
Change .logo to [word-only logo](https://www.dropbox.com/s/qrj0lid53zdddj7/BlueTechtonicaWord.png?dl=0) until we can get a new logo designed.

**Comment by hagata** [comment]
I can help with this 👍 
Looks like the only logo that needs to be changed is the header, is that correct?

The `.png` attached is OK, but if there is an SVG version, that would be nice.

As for the new logo design, is that something you need help with?

**Comment by MichelleGlauser** [comment]
Thank you! I believe it's just the header, yes. 

I have a .tif version. Is that better than .png? [You can find what we have here](https://www.dropbox.com/sh/tpk7qwf6hh4qxzx/AAAWB7dn7A6DQyJ5ICH3_nVoa?dl=0).

Help with the new logo design would be really great!

**Comment by hagata** [comment]
Thanks! I think, for the time being, the `.png`will be fine. Let's chat about the logo 👍
