### ISSUE TITLE
Add LinkedIn button

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#38]
Add a link with an icon to [our LinkedIn page](https://www.linkedin.com/company/12897075).

**Comment by akshayvinchurkar** [comment]
if I add that but where? top right or bottom as a social link

**Comment by MichelleGlauser** [comment]
With the other social links.

**Comment by akshayvinchurkar** [comment]
ok

**Comment by hagata** [comment]
@akshayvinchurkar 
There is already a PR open for this issue.
#44

**Comment by akshayvinchurkar** [comment]
that's great then merge that @MichelleGlauser
