### ISSUE TITLE
Choose and set up a new web hosting service by February 25th

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#48]
Bluehost expires on February 26th. Let's switch the website over to something new/better/cheaper before then. Several services have free or discounted plans for nonprofits, but many of them will not offer those same deals to fiscally-sponsored projects (where a project is officially part of a nonprofit that provides bookkeeping and other services, like Techtonica is with SocialGood). 

[Heroku](https://www.heroku.com/)? [Digital Ocean](https://www.digitalocean.com/) (they don't offer managed servers, but they've offered one free year with the potential for more free time, but it'd be best not to switch unless it'd still be the cheapest without that)? [Linode](https://www.linode.com/)? [Nearly Free Speech](https://www.nearlyfreespeech.net/), [SiteGround](https://www.siteground.com/non-profit-hosting.htm), [DreamHost](https://help.dreamhost.com/hc/en-us/articles/215769478-Non-profit-discount)? 

Also, since we'll be using Let's Encrypt for an SSL cert, we'll need to check which ones have support: https://community.letsencrypt.org/t/web-hosting-who-support-lets-encrypt/6920)

**Comment by MichelleGlauser** [comment]
@hagata if you could take a look at these options and share your thoughts on what would be best (least expensive and easiest to implement initially and ever after) for the existing Python/Flask site, that would be great.

**Comment by hagata** [comment]
@MichelleGlauser Will do!

**Comment by harrystaley** [comment]
Here is a list of the hosting providers that support let's encrypt.

https://community.letsencrypt.org/t/web-hosting-who-support-lets-encrypt/6920

**Comment by heyellieday** [comment]
Hey everyone, I'm making a small comparison table of potential hosting providers based on the features that are needed. Will share the link shortly!

**Comment by heyellieday** [comment]
One thing to note is beyond the hosting provider, we must take into consideration things like what DNS provider to use. @MichelleGlauser, it looks like the DNS is currently managed by Bluehost, as well. Is that correct? You bought the domain name there as well?

It may make sense to update DNS management to a provider such as Cloudflare or DNSimple that is more extensible and easier to use with technologies like Let's Encrypt. I know that there have been tools made for using Let's Encrypt on the mentioned DNS providers. DNSimple makes things very easy if you are using them for DNS: https://dnsimple.com/letsencrypt. I've used DNSimple for quite some time and they are solid option to consider for various reasons described on their site: (https://dnsimple.com/). I think the $50 a year plan would be suitable and actually supports up to 5 domains.

**Comment by heyellieday** [comment]
Also, in the future, does Techtonica plan on having additional web applications beyond the single flask app running on techtonica.org?

**Comment by MichelleGlauser** [comment]
That's right, @heyellieday, the DNS is through Bluehost. 

As far as Techtonica planning on additional web applications—I keep thinking it would be amazing to build out a larger site that has logins so people can sign up for workshops, edit their information, apply, rate students . . . it'd sure beat the mess of spreadsheets we have right now, but it's not the biggest priority right now.

**Comment by harrystaley** [comment]
We can use oauth2.0 for login and signup.

Harry Staley
(330) 718-1876
Staleyh@gmail.com

**Comment by MichelleGlauser** [comment]
@hagata, @heyellieday, and @harrystaley, the website has been phished, so it's probably best for us to choose a new hosting provider today. Ellie, can you share your table or your conclusions? Who can help get the website up and running today?

**Comment by MichelleGlauser** [comment]
From Ellie: From my initial research, Heroku can be a solid option for $0-$7 per month depending on if you want to use a free or hobby dyno, which I think in this case makes a difference for SSL stuff.
