### ISSUE TITLE
Set up SSL cert

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#49]
We can get a free SSL cert here: https://letsencrypt.org/

**Comment by harrystaley** [comment]
Let's encrypt is a great service that can be automated with a simple cron job on the server.

Apache Setup with Lets Encrypt
https://www.digitalocean.com/community/tutorials/how-to-set-up-let-s-encrypt-certificates-for-multiple-apache-virtual-hosts-on-ubuntu-14-04

Securing Nginx with Let's Encrypt
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

**Comment by MichelleGlauser** [comment]
Done when we switched the website to DreamHost.
