### ISSUE TITLE
Make site more sponsor-friendly

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#57]
We need to evaluate what potential sponsors think when they visit the site and perhaps come up with a new page, banner, or anything else that would help them decide to become sponsors.

**Comment by akshayvinchurkar** [comment]
any sponsorship plans you think about?

**Comment by MichelleGlauser** [comment]
@akshayvinchurkar: you mean, do I have an ideas about what to do to the website to make it more friendly to sponsors? Not yet.

**Comment by akshayvinchurkar** [comment]
no I mean like other websites they have sponsor plans like gold or silver ones

**Comment by MichelleGlauser** [comment]
Hi @akshayvinchurkar, I see. I'll get you the info later today! If you could fill out t[he Techtonica volunteer form](https://goo.gl/forms/jgD3BWCEg5RN8XwN2) before then, that would be great.

**Comment by MichelleGlauser** [comment]
Also, we're about to have a new video that will be perfect for this, so I hope the new design will be able to incorporate that.

**Comment by akshayvinchurkar** [comment]
@MichelleGlauser I did the form submission will you post me the link of the video design is almost finished

**Comment by MichelleGlauser** [comment]
Uploading now and will get you the link shortly. I'd love to see some screenshots of the design you're doing!

**Comment by MichelleGlauser** [comment]
Here are our sponsorship levels: http://pastebin.com/vhzXYdHn

**Comment by akshayvinchurkar** [comment]
ok @MichelleGlauser I will upload it in 2 days

**Comment by MichelleGlauser** [comment]
Hi Akshay, whoa! Thanks for taking a look at this, but I don't think we have time for a complete overhaul right now. We just need to make a link and page or section about sponsoring. Sorry I wasn't more clear about that.

For future reference, some reactions: blue over people's faces makes them look sickly. Techtonica only has one capital T (at the start). Some of the text is too small for accessibility purposes. I like the arrow over the header image to get people to the content quicker.

**Comment by akshayvinchurkar** [comment]
@MichelleGlauser we do this step by step no need to change anything just make a new branch for further development purpose i just convert this design into working site and its static one so i dont think their is any problem to do

**Comment by amychan331** [comment]
Hi! I just started to look into the Techtonica Github to see how I can help. I am looking at the Google Sponsor sign up form and notice that there is a spelling error "Latinx". As for ideas about sponsor friendly: 
- In the Google form, maybe change the sentence with "process of *applying* to sponsor" to something like "This is the first step to let us know your interest in sponsoring and hiring an awesome Techtonica student! Once we get your submission here, we will respond back [quickly / in a week] with [the next step / a form about X to fill out / more information about what's involved, etc]". That way it wouldn't sound like some long, unknown black hole process, and it shows we respect their time and busy schedule. 
- Have you consider adding a form or a sentence with email address about sponsoring space and another for services (food, drinks, etc)? I know Techtonica tweets about it, but not everyone pays attention to Twitter, and everyone loves options.
- Maybe a "Statements of Our Students" page with some quotes from students, where the sponsor can see how the students benefited from the classes? If someone is trying to get their company to sponsor, student pictures with quotes can make good visuals.

**Comment by MichelleGlauser** [comment]
Hi Amy, that's not a spelling error—google it and you'll see why we use it. I think I'm just going to change the link to that form to link to the new /sponsor/ page.

**Comment by amychan331** [comment]
Ah, I see. One learns something everyday! :D
