### ISSUE TITLE
Add Arianna Willett to Supporters

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#64]
Here's her link: https://www.linkedin.com/in/ariannawillett/ Here's her photo: https://www.dropbox.com/s/hdalbqjlqr175md/arianna-willett.jpg?dl=0

**Comment by hagata** [comment]
Approved PR #67 to fix this.

**Comment by MichelleGlauser** [comment]
Done by @amychan331 in this commit: https://github.com/MichelleGlauser/techtonica/commit/4322341796866d3451d0f73eee87cdb8c6c692ef
