### ISSUE TITLE
Remove the `/static/workshops` folder

### ISSUE THREAD

**Issue by mejarc** [MichelleGlauser/techtonica#65]
* remove workshops folder, which contains only archived image files not currently in use on web site
* remove the git commit that placed workshops into the history

cf. #17, for discussion of using filter-branch-strategy.

**Comment by mejarc** [comment]
Pull request is #66.

**Comment by hnarasaki** [comment]
Is this one done?

**Comment by mejarc** [comment]
@hnarasaki The pull request is still open, but the master branch no longer contains this folder, so can be withdrawn. Shall I do this?

**Comment by hnarasaki** [comment]
@mejarc Sure, thanks!
