### ISSUE TITLE
Content does not remain in blue hero box

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#79]
On Mobile Safari (iOS) and Mobile Chrome (Android), some of the content of the blue hero box moves outside of it (to lower on the page).

![2017-03-26 21 11 01](https://cloud.githubusercontent.com/assets/1952773/24340827/09258d48-126a-11e7-8d6a-a1be26b3982c.png)
(iOS—orange button moves down and overlaps text.)

![8bc05c40-7200-4bb6-83ea-f033e1268ef9](https://cloud.githubusercontent.com/assets/1952773/24340791/c5915abc-1269-11e7-9783-8d4a7c0635ab.jpg)
(Android—the word "you" moves down, and the orange button is overlaps text.)

**Comment by cachar** [comment]
Doesn't seem to be an issue on Mobile Safari
![image uploaded from ios](https://cloud.githubusercontent.com/assets/16581819/24391939/502fe268-1357-11e7-9232-15ce83cc348b.jpg)

**Comment by MichelleGlauser** [comment]
I'm still getting the first image on iOS Safari, but my phone is also five years old (though the software version is up-to-date). The second screenshot also still reflects the site on @michaelctsai's not-so-old OnePlus phone in Chrome. 😕
