### ISSUE TITLE
Fix design to support the same footer on all pages.

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#8]
Right now the main page and the about us pages have different background colors for the footers. How can we fix the design so the footer can always be one color?

**Comment by moagm316** [comment]
I can take care of this one with the templating in Jinja. What color do you want the footer? If you want I can make it white or blue. Whichever you want.

**Comment by MichelleGlauser** [comment]
I prefer blue, but because the last section before the footer on the main
page has a blue background, we need to figure out another design solution
first. Not sure if we should make one section have a gray background or
what.

Michelle
www.michelleglauser.com
@MichelleGlauser <https://twitter.com/MichelleGlauser>

**Comment by moagm316** [comment]
Set the footer to 90% light gray to differentiate.
