### ISSUE TITLE
Set up templating.

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#9]
With templating (perhaps with Django?) we won't have to update multiple pages with footer/header changes.

**Comment by moagm316** [comment]
What are your goals for the site? If it is just as a base website with forms then I am a big fan of Flask with Jinja. If you prefer Django I will go that route.

**Comment by MichelleGlauser** [comment]
The only reason I'd prefer Django is because that's the framework I have
experience with; but if you'd rather do Flask, that's fine, too. I'm just
really happy to have someone work on this and especially in Python. :)

Michelle
www.michelleglauser.com
@MichelleGlauser <https://twitter.com/MichelleGlauser>

**Comment by moagm316** [comment]
Base and home templates complete.

**Comment by moagm316** [comment]
Is there an image of the server that you are using so that I can test before doing a pull request?

**Comment by MichelleGlauser** [comment]
Unfortunately there is not.

**Comment by moagm316** [comment]
No worries then. I just wanted to do some testing before doing a pull request, but I am sure that you will let me know what needs to be changed prior to pushing it into production.

**Comment by MichelleGlauser** [comment]
Looks good! Running with Flask locally, I saw these things that need changing:

- "filenname" has an extra N in base.html
- "ContactUs.png" needs "img/" before it in about.html
- the commented-out section with the chalkboard icon in home.html needs a comma instead of a period not to fail, but you can just remove the whole section
- the nav links do not work correctly from the about page (clicking "How to Help" takes me to "http://localhost:5000/about/#howtohelp" and clicking "About" results in a 404)

**Comment by moagm316** [comment]
Sorry for the errors I'll have them cleaned up tonight.

Harry Staley
(330) 718-1876
Staleyh@gmail.com

**Comment by MichelleGlauser** [comment]
No problem. Thank you!

**Comment by moagm316** [comment]
Fixed the issues that you addressed.

Tested all links and the site works as requested. New vagrant VM all set up and upgraded.

Harry Staley
330-718-1876
staleyh@gmail.com <mailto:staleyh@gmail.com>
https://www.linkedin.com/in/harrystaley <https://www.linkedin.com/in/harrystaley>
